
import java.awt.Color;
import java.util.Random;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Zach
 */
public class MidTermTwo extends javax.swing.JPanel {

    /**
     * Creates new form MidTermTwo
     */
    public MidTermTwo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jButton14 = new javax.swing.JButton();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jButton17 = new javax.swing.JButton();

        setBackground(java.awt.Color.gray);

        jButton1.setBackground(java.awt.Color.orange);
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton1.setText("1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(java.awt.Color.orange);
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton2.setText("5");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(java.awt.Color.orange);
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton3.setText("9");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setBackground(java.awt.Color.orange);
        jButton4.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton4.setText("13");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setBackground(java.awt.Color.orange);
        jButton5.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton5.setText("2");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(java.awt.Color.orange);
        jButton6.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton6.setText("6");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setBackground(java.awt.Color.orange);
        jButton7.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton7.setText("10");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setBackground(java.awt.Color.orange);
        jButton8.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton8.setText("14");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(java.awt.Color.orange);
        jButton9.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton9.setText("3");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(java.awt.Color.orange);
        jButton10.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton10.setText("7");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(java.awt.Color.orange);
        jButton11.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton11.setText("11");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jButton12.setBackground(java.awt.Color.orange);
        jButton12.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton12.setText("15");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        jButton13.setBackground(java.awt.Color.orange);
        jButton13.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton13.setText("12");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });

        jButton14.setBackground(java.awt.Color.orange);
        jButton14.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton14.setText("4");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });

        jButton15.setBackground(java.awt.Color.orange);
        jButton15.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton15.setText("8");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });

        jButton16.setBackground(java.awt.Color.black);
        jButton16.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });

        jButton17.setBackground(java.awt.Color.orange);
        jButton17.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jButton17.setText("New Game");
        jButton17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                        .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton13, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(0, 0, 0)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                    .addComponent(jButton8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton16, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jButton17, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>                        

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(board[1][2] == 0){
            board[1][2] = board[1][1]; 
            board[1][1] = 0;
            switchTiles(jButton5, jButton1);
        }
        else if(board[2][1] == 0){
            board[2][1] = board[1][1];
            board[1][1] = 0;
            switchTiles(jButton2, jButton1);
        }
        checkSolution();
    }                                        

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if(board[1][3] == 0){
            board[1][3] = board[2][3]; 
            board[2][3] = 0;
            switchTiles(jButton9, jButton10);
        }
        else if(board[2][2] == 0){
            board[2][2] = board[2][3];
            board[2][3] = 0;
            switchTiles(jButton6, jButton10);
        }
        else if(board[3][3] == 0){
            board[3][3] = board[2][3]; 
            board[2][3] = 0;
            switchTiles(jButton11, jButton10);
        }
        else if(board[2][4] == 0){
            board[2][4] = board[2][3]; 
            board[2][3] = 0;
            switchTiles(jButton15, jButton10);
        }
       checkSolution(); 
    }                                         

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(board[1][2] == 0){
            board[1][2] = board[2][2]; 
            board[2][2] = 0;
            switchTiles(jButton5, jButton6);
        }
        else if(board[2][1] == 0){
            board[2][1] = board[2][2];
            board[2][2] = 0;
            switchTiles(jButton2, jButton6);
        }
        else if(board[3][2] == 0){
            board[3][2] = board[2][2]; 
            board[2][2] = 0;
           switchTiles(jButton7, jButton6);
        }
        else if(board[2][3] == 0){
            board[2][3] = board[2][2]; 
            board[2][2] = 0;
            switchTiles(jButton10, jButton6);
        }
       checkSolution(); 
    }                                        

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if(board[4][3] == 0){
            board[4][3] = board[4][4];
            board[4][4] = 0;
            switchTiles(jButton12, jButton16);
        }
        else if(board[3][4] == 0){
            board[3][4] = board[4][4]; 
            board[4][4] = 0;
            switchTiles(jButton13, jButton16);
        }
       checkSolution(); 
    }                                         

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if(board[4][4] == 0){
            board[4][4] = board[4][3]; 
            board[4][3] = 0;
            switchTiles(jButton16, jButton12);
        }
        else if(board[3][3] == 0){
            board[3][3] = board[4][3];
            board[4][3] = 0;
           switchTiles(jButton11, jButton12);
        }
        else if(board[4][2] == 0){
            board[4][2] = board[4][3]; 
            board[4][3] = 0;
            switchTiles(jButton8, jButton12);
        }
       checkSolution(); 
    }                                         

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(board[1][1] == 0){
            board[1][1] = board[2][1]; 
            board[2][1] = 0;
            switchTiles(jButton1, jButton2);
        }
        else if(board[2][2] == 0){
            board[2][2] = board[2][1];
            board[2][1] = 0;
            switchTiles(jButton6, jButton2);
        }
        else if(board[3][1] == 0){
            board[3][1] = board[2][1]; 
            board[2][1] = 0;
            switchTiles(jButton3, jButton2);
        }
       checkSolution(); 
    }                                        

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(board[2][1] == 0){
            board[2][1] = board[3][1]; 
            board[3][1] = 0;
            switchTiles(jButton2, jButton3);
        }
        else if(board[3][2] == 0){
            board[3][2] = board[3][1];
            board[3][1] = 0;
            switchTiles(jButton7, jButton3);
        }
        else if(board[4][1] == 0){
            board[4][1] = board[3][1]; 
            board[3][1] = 0;
            switchTiles(jButton4, jButton3);
        }
       checkSolution(); 
    }                                        

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(board[1][1] == 0){
            board[1][1] = board[1][2]; 
            board[1][2] = 0;
            switchTiles(jButton1, jButton5);
        }
        else if(board[2][2] == 0){
            board[2][2] = board[1][2];
            board[1][2] = 0;
            switchTiles(jButton6, jButton5);
        }
        else if(board[1][3] == 0){
            board[1][3] = board[1][2]; 
            board[1][2] = 0;
            switchTiles(jButton9, jButton5);
        }
       checkSolution(); 
    }                                        

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(board[2][2] == 0){
            board[2][2] = board[3][2]; 
            board[3][2] = 0;
            switchTiles(jButton6, jButton7);
        }
        else if(board[3][1] == 0){
            board[3][1] = board[3][2];
            board[3][2] = 0;
            switchTiles(jButton3, jButton7);
        }
        else if(board[4][2] == 0){
            board[4][2] = board[3][2]; 
            board[3][2] = 0;
            switchTiles(jButton8, jButton7);
        }
        else if(board[3][3] == 0){
            board[3][3] = board[3][2]; 
            board[3][2] = 0;
            switchTiles(jButton11, jButton7);
        }
       checkSolution(); 
    }                                        

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(board[4][1] == 0){
            board[4][1] = board[4][2]; 
            board[4][2] = 0;
            switchTiles(jButton4, jButton8);
        }
        else if(board[3][2] == 0){
            board[3][2] = board[4][2];
            board[4][2] = 0;
            switchTiles(jButton7, jButton8);
        }
        else if(board[4][3] == 0){
            board[4][3] = board[4][2]; 
            board[4][2] = 0;
            switchTiles(jButton12, jButton8);
        }
       checkSolution(); 
    }                                        

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {                                         
        if(board[1][2] == 0){
            board[1][2] = board[1][3]; 
            board[1][3] = 0;
            switchTiles(jButton5, jButton9);
        }
        else if(board[2][3] == 0){
            board[2][3] = board[1][3];
            board[1][3] = 0;
            switchTiles(jButton10, jButton9);
        }
        else if(board[1][4] == 0){
            board[1][4] = board[1][3]; 
            board[1][3] = 0;
            switchTiles(jButton14, jButton9);
        }
       checkSolution(); 
    }                                        

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if(board[2][3] == 0){
            board[2][3] = board[3][3]; 
            board[3][3] = 0;
            switchTiles(jButton10, jButton11);
        }
        else if(board[3][2] == 0){
            board[3][2] = board[3][3];
            board[3][3] = 0;
            switchTiles(jButton7, jButton11);
        }
        else if(board[4][3] == 0){
            board[4][3] = board[3][3]; 
            board[3][3] = 0;
            switchTiles(jButton12, jButton11);
        }
        else if(board[3][4] == 0){
            board[3][4] = board[3][3]; 
            board[3][3] = 0;
            switchTiles(jButton13, jButton11);
        }
       checkSolution(); 
    }                                         

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if(board[1][3] == 0){
            board[1][3] = board[1][4]; 
            board[1][4] = 0;
            switchTiles(jButton9, jButton14);
        }
        else if(board[2][4] == 0){
            board[2][4] = board[1][4];
            board[1][4] = 0;
            switchTiles(jButton15, jButton14);
        }
       checkSolution(); 
    }                                         

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if(board[1][4] == 0){
            board[1][4] = board[2][4]; 
            board[2][4] = 0;
            switchTiles(jButton14, jButton15);
        }
        else if(board[2][3] == 0){
            board[2][3] = board[2][4];
            board[2][4] = 0;
            switchTiles(jButton10, jButton15);
        }
        else if(board[3][4] == 0){
            board[3][4] = board[2][4]; 
            board[2][4] = 0;
            switchTiles(jButton13, jButton15);
        }
       checkSolution(); 
    }                                         

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        if(board[2][4] == 0){
            board[2][4] = board[3][4]; 
            board[3][4] = 0;
            switchTiles(jButton15, jButton13);
        }
        else if(board[3][3] == 0){
            board[3][3] = board[3][4];
            board[3][4] = 0;
            switchTiles(jButton11, jButton13);
        }
        else if(board[4][4] == 0){
            board[4][4] = board[3][4]; 
            board[3][4] = 0;
            switchTiles(jButton16, jButton13);
        }
       checkSolution();   
    }                                         

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {                                         
         if(board[3][1] == 0){
            board[3][1] = board[4][1];
            board[4][1] = 0;
            switchTiles(jButton3, jButton4);
        }
         else if (board[4][2] == 0){
            board[4][2] = board[4][1]; 
            board[4][1] = 0;
            switchTiles(jButton8, jButton4);
        }
       checkSolution();  
    }                                        

    private void jButton17ActionPerformed(java.awt.event.ActionEvent evt) {                                          
        shuffle();
    }                                         


    // Variables declaration - do not modify                     
    private static javax.swing.JButton jButton1;
    private static javax.swing.JButton jButton10;
    private static javax.swing.JButton jButton11;
    private static javax.swing.JButton jButton12;
    private static javax.swing.JButton jButton13;
    private static javax.swing.JButton jButton14;
    private static javax.swing.JButton jButton15;
    private static javax.swing.JButton jButton16;
    private javax.swing.JButton jButton17;
    private static javax.swing.JButton jButton2;
    private static javax.swing.JButton jButton3;
    private static javax.swing.JButton jButton4;
    private static javax.swing.JButton jButton5;
    private static javax.swing.JButton jButton6;
    private static javax.swing.JButton jButton7;
    private static javax.swing.JButton jButton8;
    private static javax.swing.JButton jButton9;
    // End of variables declaration                   


   
   int[][] board = {{-1,-1,-1,-1,-1,-1},{-1,1,2,3,4,-1},{-1,5,6,7,8,-1},{-1,9,10,11,12,-1},{-1,13,14,15,0,-1},{-1,-1,-1,-1,-1,-1}};
  
   public static void main(String[] args) {
       MidTermTwo zach = new MidTermTwo();
       zach.createJFrame();
       
   }
   
   public void createJFrame(){
       JFrame tileGame = new JFrame();
       MidTermTwo zach = new MidTermTwo();
       tileGame.add(zach);
       tileGame.pack();
       tileGame.setVisible(true);
       tileGame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
   }
   
   public void switchTiles(JButton buttonOldZero, JButton buttonNewZero){
       buttonOldZero.setText(buttonNewZero.getText());
       buttonNewZero.setText(null);
       buttonNewZero.setBackground(Color.BLACK);
       buttonOldZero.setBackground(Color.ORANGE);
    }
   
   public void shuffle(){
     for(int i=1; i<1000000; i++){
       double randomNumber = (int)(Math.random()*(16) + 0);
      
       if(randomNumber == 0){
           if(board[1][2] == 0){
            board[1][2] = board[1][1]; 
            board[1][1] = 0;
            switchTiles(jButton5, jButton1);
            }
            else if(board[2][1] == 0){
                board[2][1] = board[1][1];
                board[1][1] = 0;
                switchTiles(jButton2, jButton1);
            }    
        }
       else if(randomNumber ==1){
           if(board[1][1] == 0){
                board[1][1] = board[2][1]; 
                board[2][1] = 0;
                switchTiles(jButton1, jButton2);
            }
            else if(board[2][2] == 0){
                board[2][2] = board[2][1];
                board[2][1] = 0;
                switchTiles(jButton6, jButton2);
            }
            else if(board[3][1] == 0){
                board[3][1] = board[2][1]; 
                board[2][1] = 0;
                switchTiles(jButton3, jButton2);
        }
        
           
       }
       
       else if (randomNumber == 2){
           if(board[2][1] == 0){
                board[2][1] = board[3][1]; 
                board[3][1] = 0;
                switchTiles(jButton2, jButton3);
            }
            else if(board[3][2] == 0){
                board[3][2] = board[3][1];
                board[3][1] = 0;
                switchTiles(jButton7, jButton3);
            }
            else if(board[4][1] == 0){
                board[4][1] = board[3][1]; 
                board[3][1] = 0;
                switchTiles(jButton4, jButton3);
            }

           }
       
       else if (randomNumber == 3){
           if(board[3][1] == 0){
                board[3][1] = board[4][1];
                board[4][1] = 0;
                switchTiles(jButton3, jButton4);
            }
             else if (board[4][2] == 0){
                board[4][2] = board[4][1]; 
                board[4][1] = 0;
                switchTiles(jButton8, jButton4);
            }

           }
       
       else if(randomNumber == 4){
           if(board[1][1] == 0){
                board[1][1] = board[1][2]; 
                board[1][2] = 0;
                switchTiles(jButton1, jButton5);
            }
            else if(board[2][2] == 0){
                board[2][2] = board[1][2];
                board[1][2] = 0;
               switchTiles(jButton6, jButton5);
            }
            else if(board[1][3] == 0){
                board[1][3] = board[1][2]; 
                board[1][2] = 0;
                switchTiles(jButton9, jButton5);
            }

           }
       
       else if (randomNumber == 5){
           if(board[1][2] == 0){
                board[1][2] = board[2][2]; 
                board[2][2] = 0;
                switchTiles(jButton5, jButton6);
            }
            else if(board[2][1] == 0){
                board[2][1] = board[2][2];
                board[2][2] = 0;
                switchTiles(jButton2, jButton6);
            }
            else if(board[3][2] == 0){
                board[3][2] = board[2][2]; 
                board[2][2] = 0;
                switchTiles(jButton7, jButton6);
            }
            else if(board[2][3] == 0){
                board[2][3] = board[2][2]; 
                board[2][2] = 0;
                switchTiles(jButton10, jButton6);
            }

           }
       
       else if (randomNumber == 6){
           if(board[2][2] == 0){
                board[2][2] = board[3][2]; 
                board[3][2] = 0;
                switchTiles(jButton6, jButton7);
            }
            else if(board[3][1] == 0){
                board[3][1] = board[3][2];
                board[3][2] = 0;
                switchTiles(jButton3, jButton7);
            }
            else if(board[4][2] == 0){
                board[4][2] = board[3][2]; 
                board[3][2] = 0;
                switchTiles(jButton8, jButton7);
            }
            else if(board[3][3] == 0){
                board[3][3] = board[3][2]; 
                board[3][2] = 0;
               switchTiles(jButton11, jButton7);
            }

           }
       
       else if (randomNumber == 7){
            if(board[4][1] == 0){
                board[4][1] = board[4][2]; 
                board[4][2] = 0;
                switchTiles(jButton4, jButton8);
            }
            else if(board[3][2] == 0){
                board[3][2] = board[4][2];
                board[4][2] = 0;
                switchTiles(jButton7, jButton8);
            }
            else if(board[4][3] == 0){
                board[4][3] = board[4][2]; 
                board[4][2] = 0;
                switchTiles(jButton12, jButton8);
            }

           }
       
       else if(randomNumber == 8){
           if(board[1][2] == 0){
                board[1][2] = board[1][3]; 
                board[1][3] = 0;
               switchTiles(jButton5, jButton9);
            }
            else if(board[2][3] == 0){
                board[2][3] = board[1][3];
                board[1][3] = 0;
                switchTiles(jButton10, jButton9);
            }
            else if(board[1][4] == 0){
                board[1][4] = board[1][3]; 
                board[1][3] = 0;
                switchTiles(jButton14, jButton9);
            }

           }

           else if(randomNumber == 9){
               if(board[1][3] == 0){
                board[1][3] = board[2][3]; 
                board[2][3] = 0;
                switchTiles(jButton9, jButton10);
            }
            else if(board[2][2] == 0){
                board[2][2] = board[2][3];
                board[2][3] = 0;
                switchTiles(jButton6, jButton10);
            }
            else if(board[3][3] == 0){
                board[3][3] = board[2][3]; 
                board[2][3] = 0;
                switchTiles(jButton11, jButton10);
            }
            else if(board[2][4] == 0){
                board[2][4] = board[2][3]; 
                board[2][3] = 0;
                switchTiles(jButton15, jButton10);
            }

           }

           else if(randomNumber ==10){
               if(board[2][3] == 0){
                board[2][3] = board[3][3]; 
                board[3][3] = 0;
                switchTiles(jButton10, jButton11);
            }
            else if(board[3][2] == 0){
                board[3][2] = board[3][3];
                board[3][3] = 0;
                switchTiles(jButton7, jButton11);
            }
            else if(board[4][3] == 0){
                board[4][3] = board[3][3]; 
                board[3][3] = 0;
                switchTiles(jButton12, jButton11);
            }
            else if(board[3][4] == 0){
                board[3][4] = board[3][3]; 
                board[3][3] = 0;
                switchTiles(jButton13, jButton11);
            }

           }
       
       else if(randomNumber == 11){
           if(board[4][4] == 0){
                board[4][4] = board[4][3]; 
                board[4][3] = 0;
                switchTiles(jButton16, jButton12);
            }
            else if(board[3][3] == 0){
                board[3][3] = board[4][3];
                board[4][3] = 0;
               switchTiles(jButton11, jButton12);
            }
            else if(board[4][2] == 0){
                board[4][2] = board[4][3]; 
                board[4][3] = 0;
                switchTiles(jButton8, jButton12);
            }

           }
       
       else if(randomNumber == 12){
           if(board[2][4] == 0){
                board[2][4] = board[3][4]; 
                board[3][4] = 0;
                switchTiles(jButton15, jButton13);
            }
            else if(board[3][3] == 0){
                board[3][3] = board[3][4];
                board[3][4] = 0;
                switchTiles(jButton11, jButton13);
            }
            else if(board[4][4] == 0){
                board[4][4] = board[3][4]; 
                board[3][4] = 0;
                switchTiles(jButton16, jButton13);
            }

           }
       
       else if(randomNumber == 13){
           if(board[1][3] == 0){
                board[1][3] = board[1][4]; 
                board[1][4] = 0;
                switchTiles(jButton9, jButton14);
            }
            else if(board[2][4] == 0){
                board[2][4] = board[1][4];
                board[1][4] = 0;
                switchTiles(jButton15, jButton14);
            }

           }
       
       else if(randomNumber == 14){
           if(board[1][4] == 0){
                board[1][4] = board[2][4]; 
                board[2][4] = 0;
                switchTiles(jButton14, jButton15);
            }
            else if(board[2][3] == 0){
                board[2][3] = board[2][4];
                board[2][4] = 0;
                switchTiles(jButton10, jButton15);
            }
            else if(board[3][4] == 0){
                board[3][4] = board[2][4]; 
                board[2][4] = 0;
                switchTiles(jButton13, jButton15);
            }

           }
       
       else if(randomNumber == 15){
           if(board[4][3] == 0){
                board[4][3] = board[4][4];
                board[4][4] = 0;
                switchTiles(jButton12, jButton16);
            }
            else if(board[3][4] == 0){
                board[3][4] = board[4][4]; 
                board[4][4] = 0;
                switchTiles(jButton13, jButton16);
            }
           }
      }
   }
   
   public void checkSolution(){
       if(board[1][1] == 1 & board[1][2] == 2 & board[1][3] == 3 & board[1][4] == 4 
               & board [2][1] == 5 & board[2][2] == 6 & board[2][3] == 7 & board[2][4] == 8
               & board [3][1] == 9 & board[3][2] == 10 & board[3][3] == 11 &board[3][4] == 12
               & board[4][1] == 13 & board [4][2] == 14 & board[4][3] == 15){
            
           JOptionPane.showMessageDialog(null, "YOU DID IT!!!!");
           System.exit(0);
       }
      
   }

}
